import React, { useState } from 'react';
import VisitorService from '../services/visitor.service';

const RegisterVisitor = () => {
  const initialFormState = {
    name: '',
    mobile: '',
    email: '',
    companyName: '',
    purpose: '',
    personToMeet: '',
    department: '',
    visitDate: new Date().toISOString().split('T')[0],
    expectedTime: new Date().toTimeString().split(' ')[0].slice(0, 5), // E.g., "14:30"
    idProofType: 'Aadhaar Card',
    idNumber: '',
    photo: '',
  };

  const [formData, setFormData] = useState(initialFormState);
  const [photoPreview, setPhotoPreview] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  // Convert uploaded image to Base64 string
  const handlePhotoChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        setError('Photo size should be less than 5MB.');
        return;
      }
      
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData((prev) => ({
          ...prev,
          photo: reader.result,
        }));
        setPhotoPreview(reader.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleReset = () => {
    setFormData(initialFormState);
    setPhotoPreview('');
    setError('');
    setSuccess('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    // Field Validations
    if (!formData.name || !formData.mobile || !formData.email || !formData.purpose || 
        !formData.personToMeet || !formData.department || !formData.visitDate || 
        !formData.expectedTime || !formData.idProofType || !formData.idNumber) {
      setError('Please fill in all mandatory fields.');
      return;
    }

    setLoading(true);
    try {
      const savedVisitor = await VisitorService.registerVisitor(formData);
      setSuccess(`Visitor registered successfully with ID Code: ${savedVisitor.visitorCode}`);
      // Clear form
      setFormData(initialFormState);
      setPhotoPreview('');
    } catch (err) {
      setError(err.response?.data?.message || 'Error occurred while saving visitor details.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page-wrapper">
      <div className="page-header-row">
        <h2>Register Visitor</h2>
        <p>Register a new visitor entry details in the system</p>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}
      {success && <div className="alert alert-success">{success}</div>}

      <form onSubmit={handleSubmit} className="visitor-register-form">
        <div className="form-section-title">Visitor Information</div>
        <div className="form-grid-3">
          <div className="form-group">
            <label htmlFor="visitorCode">Visitor Code</label>
            <input
              type="text"
              id="visitorCode"
              value="Auto-Generated by System"
              disabled
              className="disabled-input"
            />
          </div>

          <div className="form-group">
            <label htmlFor="name">Visitor Name <span className="required-star">*</span></label>
            <input
              type="text"
              id="name"
              name="name"
              value={formData.name}
              onChange={handleChange}
              placeholder="Full name of visitor"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="mobile">Mobile Number <span className="required-star">*</span></label>
            <input
              type="tel"
              id="mobile"
              name="mobile"
              value={formData.mobile}
              onChange={handleChange}
              placeholder="10-digit mobile number"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email Address <span className="required-star">*</span></label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              placeholder="visitor@company.com"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="companyName">Company Name</label>
            <input
              type="text"
              id="companyName"
              name="companyName"
              value={formData.companyName}
              onChange={handleChange}
              placeholder="Visitor's company name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="idProofType">ID Proof Type <span className="required-star">*</span></label>
            <select
              id="idProofType"
              name="idProofType"
              value={formData.idProofType}
              onChange={handleChange}
              required
            >
              <option value="Aadhaar Card">Aadhaar Card</option>
              <option value="PAN Card">PAN Card</option>
              <option value="Passport">Passport</option>
              <option value="Driving License">Driving License</option>
              <option value="Voter ID">Voter ID</option>
              <option value="Office ID Card">Office ID Card</option>
            </select>
          </div>

          <div className="form-group">
            <label htmlFor="idNumber">ID Proof Number <span className="required-star">*</span></label>
            <input
              type="text"
              id="idNumber"
              name="idNumber"
              value={formData.idNumber}
              onChange={handleChange}
              placeholder="Enter ID card number"
              required
            />
          </div>
        </div>

        <div className="form-section-title">Visit Details</div>
        <div className="form-grid-3">
          <div className="form-group">
            <label htmlFor="personToMeet">Person to Meet <span className="required-star">*</span></label>
            <input
              type="text"
              id="personToMeet"
              name="personToMeet"
              value={formData.personToMeet}
              onChange={handleChange}
              placeholder="Host/Employee name"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="department">Department <span className="required-star">*</span></label>
            <select
              id="department"
              name="department"
              value={formData.department}
              onChange={handleChange}
              required
            >
              <option value="">Select Department</option>
              <option value="HR / Recruitment">HR / Recruitment</option>
              <option value="IT / Software Engineering">IT / Software Engineering</option>
              <option value="Sales / Marketing">Sales / Marketing</option>
              <option value="Finance / Accounts">Finance / Accounts</option>
              <option value="Operations / Admin">Operations / Admin</option>
              <option value="Executive Management">Executive Management</option>
            </select>
          </div>

          <div className="form-group double-span">
            <label htmlFor="purpose">Purpose Of Visit <span className="required-star">*</span></label>
            <input
              type="text"
              id="purpose"
              name="purpose"
              value={formData.purpose}
              onChange={handleChange}
              placeholder="E.g., Business Meeting, Job Interview, Delivery, Maintenance"
              required
            />
          </div>
        </div>

        <div className="form-section-title">Visitor Photo</div>
        <div className="form-photo-upload-section">
          <div className="form-group">
            <label htmlFor="photo">Upload Visitor Photo</label>
            <input
              type="file"
              id="photo"
              accept="image/*"
              onChange={handlePhotoChange}
              className="file-input"
            />
            <small className="help-text-block">Upload a clear mugshot photo of the visitor (Max 5MB)</small>
          </div>
          {photoPreview && (
            <div className="photo-upload-preview-box">
              <span className="preview-label">Photo Preview:</span>
              <img src={photoPreview} alt="Preview" className="uploaded-photo-preview" />
            </div>
          )}
        </div>

        <div className="form-actions-row">
          <button type="submit" className="btn btn-primary" disabled={loading}>
            {loading ? 'Saving Visitor...' : 'Save Visitor'}
          </button>
          <button type="button" onClick={handleReset} className="btn btn-secondary">
            Reset
          </button>
        </div>
      </form>
    </div>
  );
};

export default RegisterVisitor;
